<a href="https://colab.research.google.com/github/GulshanYasmeen/AI-DSA/blob/main/Iris_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# -*- coding: utf-8 -*-
"""Classification_with_Neural_Networks_using_Tensorflow

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z0ddq6svHLGsHLhRFUcyGndlCCM3ds9A

# Lab Overview
In this lab, you will learn how to apply neural networks for classification tasks using the Iris flower dataset. The Iris dataset contains measurements of four features of different iris flowers: sepal length, sepal width, petal length, and petal width. Our goal is to train a neural network model to classify the iris flowers into three different species: Setosa, Versicolor, and Virginica.

## Step 1: Import Libraries
We'll start by importing the necessary libraries. In this lab, we'll be using TensorFlow, NumPy, and scikit-learn.
"""

import tensorflow as tf
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [3]:
"""## Step 2: Load and Preprocess the Dataset
Next, we'll load the Iris dataset and preprocess it. We'll split the dataset into training and testing sets and perform one-hot encoding on the target labels.
"""

# Load the Iris dataset
iris = load_iris()

#print(iris)

In [4]:
# Split the dataset into features and labels
X = iris.data
y = iris.target.reshape(-1, 1)

print(X)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [6]:
# We can also convert this X and Y array to Pandas DataFrame
import pandas as pd

df = pd.DataFrame(data=X, columns=["Sepal_length", "Sepal_width", "Petal_length", "Petal_width"])
df["Species"] = y
df

Sepal_length  Sepal_width  Petal_length  Petal_width  Species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [ ]:
df.shape

df.isnull().sum()

In [ ]:
# Perform one-hot encoding on the target labels
encoder = OneHotEncoder(categories="auto")
y = encoder.fit_transform(y).toarray()
y

In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Define the model architecture
import tensorflow as tf
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, input_shape=(4,), activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
])

model.summary()

In [ ]:
"""## Step 4: Compile and Train the Model
Next, we'll compile the model by specifying the loss function, optimizer, and evaluation metric. Then, we'll train the model on the training data.
"""

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=50, batch_size=8, verbose=1)

In [ ]:
import matplotlib.pyplot as plt

# Extract loss and accuracy values from the training history
loss = history.history['loss']
accuracy = history.history['accuracy']

In [ ]:
# Plot the loss
plt.figure(figsize=(10, 5))
plt.plot(range(1, len(loss) + 1), loss, color='blue')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.title('Training Loss')
plt.grid(True)
plt.show()

In [ ]:
# Plot the accuracy
plt.figure(figsize=(10, 5))
plt.plot(range(1, len(accuracy) + 1), accuracy, color='red')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.title('Training Accuracy')
plt.grid(True)
plt.show()

In [ ]:
"""## Step 5: Evaluate the Model
After training, we'll evaluate the model's performance on the testing data and calculate the accuracy.
"""

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

In [ ]:
"""## Step 6: Make Predictions
Finally, we can use the trained model to make predictions on new data.
"""

# Make predictions
predictions = model.predict(X_test)
print(predictions)

predicted_labels = np.argmax(predictions, axis=1)
print(predicted_labels)

In [ ]:
from sklearn.metrics import confusion_matrix
import seaborn as sns

# Compute the confusion matrix
cm = confusion_matrix(np.argmax(y_test, axis=1), predicted_labels)

# Plot the confusion matrix using a heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, cmap='Blues', fmt='d', xticklabels=iris.target_names, yticklabels=iris.target_names)
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')
plt.title('Confusion Matrix')
plt.show()